# Generated by Django 5.1.1 on 2024-09-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_alter_mailmessage_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaccount',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
